USE dbFinanceiro
GO

CREATE TABLE Etnia
(
    Codigo INT IDENTITY(1,1) PRIMARY KEY,

    Descricao VARCHAR(100) NOT NULL
)
GO

ALTER TABLE FUNCIONARIO
ADD CodigoEtnia INT
GO

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_ETNIA
FOREIGN KEY (CodigoEtnia)
REFERENCES Etnia(Codigo)
GO