USE dbFinanceiro
GO

CREATE TABLE Escolaridade
(
    Codigo INT IDENTITY(1,1) PRIMARY KEY,

    Descricao VARCHAR(100) NOT NULL
)
GO

ALTER TABLE FUNCIONARIO
ADD CodigoEscolaridade INT
GO

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_ESCOLARIDADE
FOREIGN KEY (CodigoEscolaridade)
REFERENCES Escolaridade(Codigo)
GO