USE [dbFinanceiro]
GO

/****** Object:  Table [dbo].[ESTADO]    Script Date: 11/05/2026 08:19:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ESTADO](
	[Codigo] [int] IDENTITY(1,1) NOT NULL,
	[NomeEstado] [varchar](100) NOT NULL,
	[Sigla] [varchar](2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

